edit jenkinsfile #final

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -15,10 +15,6 @@ pipeline {
                     deleteDir()  // Clears workspace before checking out repo
                     git branch: BRANCH_NAME, credentialsId: 'github_token', url: GIT_REPO_URL
                     echo "Repository checkout successful"
-                    // Set GIT_COMMIT variable
-                    //env.GIT_COMMIT = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
-                    //sh "echo Checked out commit: ${env.GIT_COMMIT}"
-                    // Set IMAGE_NAME variable
                     env.IMAGE_NAME = "${DOCKER_HUB_REPO}/${TECHNOLOGY_NAME}:latest"
                     sh "echo Global Image Name: ${env.IMAGE_NAME}"
                 }
@@ -62,10 +58,14 @@ pipeline {
               retry(2) // retry this stage up to 2 more times if it fails
             }
             steps {
-                script {
+                 withCredentials([usernamePassword(
+                    credentialsId: 'aws-credentials', 
+                    usernameVariable: 'AWS_ACCESS_KEY_ID',
+                    passwordVariable: 'AWS_SECRET_ACCESS_KEY'
+                )]) {
                         sh """
                            terraform init -reconfigure
-                           terraform apply
+                           terraform apply -auto-approve
                         """
                 }
             }
@@ -75,14 +75,52 @@ pipeline {
 
     post {
       always {
-        // Clean up Docker images
-        script {
-        echo "Cleaning up Docker images to free disk space..."
-        // Remove the image built in this pipeline
-        sh "docker rmi -f ${env.IMAGE_NAME} || true"
-        // Remove dangling images that don’t have a tag (their tag shows as <none>)
-        sh "docker image prune -f"
-        }
-      }
+       script {
+         echo "Cleaning up Docker images to free disk space..."
+         // Remove the image built in this pipeline
+         sh "docker rmi -f ${env.IMAGE_NAME} || true"
+         // Remove dangling images
+         sh "docker image prune -f"
+
+         // Get build status
+         def status = currentBuild.currentResult
+
+         // Initialize IPs
+         def masterIp = "N/A"
+         def workerIp = "N/A"
+         def prometheusIp = "N/A"
+
+         // Get Terraform output
+         try {
+          withCredentials([usernamePassword(
+                    credentialsId: 'aws-credentials', 
+                    usernameVariable: 'AWS_ACCESS_KEY_ID',
+                    passwordVariable: 'AWS_SECRET_ACCESS_KEY'
+                )]) {
+           def tfOutput = sh(script: 'terraform output -json', returnStdout: true).trim()
+           def json = readJSON text: tfOutput
+           masterIp = json.master_server_public_ip.value
+           workerIp = json.worker_server_public_ip.value
+           prometheusIp = json.prometheus_server_public_ip.value
+         }} catch (err) {
+         echo "Terraform output fetch failed: ${err.getMessage()}"
+         }
+
+         // Slack notification
+         def color = (status == 'SUCCESS') ? 'good' : 'danger'
+
+         slackSend (
+          color: color,
+          message: """ 
+          *Build Status:* ${status}
+          *App URL:* http://${workerIp}:30004
+          *Master IP:* ${masterIp}
+          *Worker IP:* ${workerIp}
+          *Prometheus IP:* ${prometheusIp}
+          """
+      )
     }
+  }
+}
+
 }
